apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: my-project
spec:
  selector:
    app: flask-api-test  # This matches the label in your Flask deployment
  ports:
    - protocol: TCP
      port: 5000  # The service port
      targetPort: 5000  # The container port Flask is running on
  type: ClusterIP  # Exposes service within the cluster only
