apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-project
spec:
  selector:
    app: frontend-test  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 3000 
  type: LoadBalancer 
