apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-test
  template:
    metadata:
      labels:
        app: frontend-test
    spec:
      containers:
      - name: frontend-test
        image: hitmanrodent47/frontend-test:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-project
spec:
  selector:
    app: frontend-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
